name: "Create Repository"
description: "Use this issue to request a new GitHub Repository"
title: "Repository creation request"
labels: ["repo-creation"]
body:
- type: markdown
  attributes:
    value: |
      This should read: "Please enter the Solution Asset ID associated with your team's [GitHub Product Code](https://wiki.fisglobal.com/display/cmtech/GHE+-+Team+Onboarding#GHETeamOnboarding-GitHubProductCode) and the name, description, BUC code to create a repository."
- type: dropdown
  id: buc-dd
  attributes:
    label: BUC Code
    options:
      - DEE - 1001.510050.9976
      - DRCB - 1001.510050.9326
      - DLFI - 3002.510050.9722
      - DBTVS - 1001.510050.9775
      - BPS - 1001.510050.9770
      - DBUS - 3801.510050.9975
  validations:
    required: true
- type: input
  id: repo-name
  attributes:
    label: Repository Name
    description: Enter the name of the repository(max 60 chars and no special characters) **(mandatory)**
    placeholder: ex. ui
  validations:
    required: true
- type: dropdown
  id: visibility
  attributes:
    label: Visibility
    multiple: false
    description: Please select the visibility **(default is private)**
    default: 0
    options:
      - private
      - internal
  validations:
    required: true
- type: textarea
  id: repo-description
  attributes:
    label: Repo Description
    description: Describe the use of the repository and what it will hold **(mandatory)**
  validations:
    required: true
