name: "Create New Repository"
description: "Submit a request to create a new repository."
title: "Repository Creation Request"
labels: ["repo-request"]
body:
 - type: input
   id: repo_name
   attributes:
     label: "Repository Name"
     description: "Enter the name of the repository to be created."
     placeholder: "my-new-repo"
     required: true
 - type: input
   id: repo_description
   attributes:
     label: "Repository Description"
     description: "Provide a brief description of the repository."
     placeholder: "This repository is for..."
     required: true
 - type: dropdown
   id: repo_visibility
   attributes:
     label: "Repository Visibility"
     options:
       - "Public"
       - "Private"
     required: true
